backend:
  name: git-gateway
  branch: main  # or 'master' depending on your repo

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
